"""Added roles and bcrypt hashing

Revision ID: 01738e19f15b
Revises: 2ca7ea87a329
Create Date: 2026-03-04 12:19:54.619906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01738e19f15b'
down_revision = '2ca7ea87a329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
